### ISSUE TITLE
Firebase Storage Compile error

### ISSUE THREAD

**Issue by aliyildiz1980** [dkimitsa/robovm-robopods#20] opened 2022-12-31 20:58 UTC
Hi,

I am struggling with a compile error when I add firebase storage robopod to my android project. I am using Android Studio  2021.3.1 Patch 1, Gradle 7.4, RoboVM plugin 2.3.18. When I add "io.github.dkimitsa.robovm:robopods-firebase-storage-ios:1.28.0-SNAPSHOT" to app gradle file, I get the following error. I removed all other robopods to see if the error is related with other robopods. But, the result is the same.

Frameworks that I use (Firabase version 10.3.0):
FirebaseStorage
GTMSessionFetcher
GoogleUtilities
FBLPromises
FirebaseCore
FirebaseCoreInternal

[ERROR] Couldn't compile app
org.apache.commons.exec.ExecuteException: Command '[/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo, /Users/XXX/Development/YYY/ios/robovm-build/tmp/iOS/ios/arm64-simulator/IOSLauncher.app/Frameworks/libswiftCore.dylib, -remove, i386, -remove, x86_64, -output, /Users/aliyildiz/Development/YYY/ios/robovm-build/tmp/iOS/ios/arm64-simulator/IOSLauncher.app/Frameworks/libswiftCore.dylib.tmp]' failed  (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.robovm.compiler.util.Executor.exec(Executor.java:344)
	at org.robovm.compiler.util.ToolchainUtil.lipoRemoveArchs(ToolchainUtil.java:332)
	at org.robovm.compiler.target.AbstractTarget.stripExtraArches(AbstractTarget.java:704)
	at org.robovm.compiler.target.AbstractTarget.copySwiftLibs(AbstractTarget.java:675)
	at org.robovm.compiler.target.AbstractTarget.copyDynamicFrameworks(AbstractTarget.java:406)
	at org.robovm.compiler.target.AbstractTarget.doInstall(AbstractTarget.java:772)
	at org.robovm.compiler.target.AbstractTarget.doInstall(AbstractTarget.java:761)
	at org.robovm.compiler.target.ios.IOSTarget.prepareLaunch(IOSTarget.java:389)
	at org.robovm.compiler.target.ios.IOSTarget.prepareLaunch(IOSTarget.java:384)
	at org.robovm.idea.compilation.RoboVmCompileTask$3.doCompile(RoboVmCompileTask.java:282)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:69)

**Comment by dkimitsa** [comment] 2023-01-03 07:33
what version of xcode do you use ? 
as if fails on stripping simulator architectures from swift libraries

**Comment by aliyildiz1980** [comment] 2023-01-03 08:53
I am using XCode v14.2 (14C18)

**Comment by dkimitsa** [comment] 2023-01-03 10:52
its not pods related by compiler itself. 
can you please share a sample project  to reproduce ? as I can see you are building for arm64-simulator and for simulator target strip() should not be executed

**Comment by aliyildiz1980** [comment] 2023-01-03 12:38
Yes. I am building for arm64-simulator. For real devices, compile seems to be fine (though I haven't installed and tried the build). I have attached an example project. It is an empty LibGDX project created with gdx-setup tool with the following modifications:
1) implementation "io.github.dkimitsa.robovm:robopods-firebase-storage-ios:$altpodsVersion" is added to build.gradle file.
2) <swiftSupport/> and <frameworkPaths> <path variant="device">libs/arm</path> <path variant="simulator">libs/sim</path> </frameworkPaths> lines are added to robovm.properties file.
3) Necessary frameworks are copied to ios/libs folder.

[test.zip](https://github.com/dkimitsa/robovm-robopods/files/10336561/test.zip)

**Comment by dkimitsa** [comment] 2023-01-03 15:05
thanks, are you starting it with gradle script or from Idea plugin?

**Comment by dkimitsa** [comment] 2023-01-03 15:30
ok, its a bug that was fixed in 2.3.19-SNAPSHOT
here is a PR for reference 
https://github.com/MobiVM/robovm/pull/671/files
closing it as its not alt-pods bug

**Closed as completed by dkimitsa** 2023-01-03 15:30 UTC

**Comment by aliyildiz1980** [comment] 2023-01-03 19:27
Hi again,

I tried with MobiVM 2.3.19-SNAPSHOT. But, the same error occurs.

**Comment by dkimitsa** [comment] 2023-01-03 21:07
how exactly have you tried? 
if you run with pure gradle  -- make sure that you have correct version in plugin dependency:
>         classpath "com.mobidevelop.robovm:robovm-gradle-plugin:${roboVMVersion}"

if you run in Idea -- make sure that you have installed proper version of plugin from here 
https://mobivm.github.io/downloads.html?prefix=snapshots/idea

**Comment by aliyildiz1980** [comment] 2023-01-04 08:46
I am using gradle. Changing gradle plugin version didn't work, either.

classpath 'com.mobidevelop.robovm:robovm-gradle-plugin:2.3.19-SNAPSHOT'

**Comment by dkimitsa** [comment] 2023-01-04 09:39
there seems to be an issue when using tree-shaker. 
try disabling it in robovm.xml
```
 <!--  <treeShaker>conservative</treeShaker> -->
```
meanwhile I will check why it cause an issue

**Comment by aliyildiz1980** [comment] 2023-01-04 09:49
I tried building without treeshaker. The problem is still there. I tried with both 2.3.18 and 2.3.19-SNAPSHOT

**Comment by dkimitsa** [comment] 2023-01-04 09:54
could you please run with info/stackrace params ? 
> ./gradlew --info --stacktrace launchIPhoneSimulator

as your sample is working for me

**Comment by aliyildiz1980** [comment] 2023-01-04 10:14
The build succeded after a clean build with 2.3.19-SNAPSHOT and without treeshaker. Thanks for your support. Do you want me to open an issue in MobiVM repository for treeshaker bug?

**Comment by dkimitsa** [comment] 2023-01-04 10:20
already looking for it, but please open an issue, thx !

**Comment by aliyildiz1980** [comment] 2023-01-04 10:44
Issue #699 is created:

https://github.com/MobiVM/robovm/issues/699

**Comment by dkimitsa** [comment] 2023-01-04 11:01
thx, the fix: https://github.com/MobiVM/robovm/pull/700
